### ISSUE TITLE
unable to start appimage on unbuntu 1804

### ISSUE THREAD

**Issue by nephaste** [Sn8z/Poddr#64]
hi 

i try integrate Poddr to Qnap HDStation (ubuntu1804)

`root@TS253:/opt/Poddr# ./poddr..AppImage
desktop-file-install is missing. Skipping /tmp/.mount_poddr.2ajYIT/AppRun.
[14:56:43.463] [error] Error: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
    at new module.exports (/tmp/.mount_poddr.2ajYIT/resources/app.asar/node_modules/dbus/lib/bus.js:24:27)
    at Function.DBus.getBus (/tmp/.mount_poddr.2ajYIT/resources/app.asar/node_modules/dbus/lib/dbus.js:39:9)
    at App.<anonymous> (/tmp/.mount_poddr.2ajYIT/resources/app.asar/main.js:70:26)
    at Object.onceWrapper (events.js:273:13)
    at App.emit (events.js:187:15)

[14:56:46.344] [info] Settings are stored at /root/.config/poddr/storage
[14:56:46.645] [info] Fetching storefronts...
[14:56:46.750] [info] Done fetching storefronts.
[14:56:47.170] [info] Loaded CSS color variable.
[14:56:47.196] [info] Fetching podcasts...
[14:56:47.709] [info] Found 50 podcasts.
`

only get a black screen

**Comment by Sn8z** [comment]
Hi @nephaste!
I'm struggling to replicate your issue on my own Ubuntu 18.04 machine. The error in your provided log is weird but it shouldn't prevent Poddr from starting up.
* What version of Poddr are you using? If you are using 1.0.9 could you try and see if 1.0.8 works better for you?
* You could also try and install the snap version of Poddr by running `snap install poddr`
* Have it worked before or did it start to crash suddenly?
* Does other AppImage programs work correctly for you?

Thanks for using Poddr and reporting your issue :)

**Comment by nephaste** [comment]
Hi thanks for reply

i tested the 1.0.9 not tried the 1.0.8..

was my first try with your application

the goal is to provide to Qnap NAS users a Poddr qpkg communinty install into HDStation which is an Ubuntu 18.04 chroot

the system is a bit closed (no apt-get for exemple and all must run as root) and dont have possibility to create a qpkg with snap

I already built Appimage and also used somes for other dev with no issue in most of case

**Comment by nephaste** [comment]
just fixed it ... all is working was strange

i rename with typo error with 2 x. "podrr..AppImage"  , i renamed it into "podrr.Appimage"  and all is starting fine 

Qnap users will be Happy with this new qpkg many thanks
